Julwicr/treehouses

- app/controllers/bookings_controller.rb
- app/models/booking.rb
- app/models/treehouse.rb
- db/migrate/20220523175137_create_bookings.rb
- test/controllers/bookings_controller_test.rb
- test/models/booking_test.rb
add booking model and controller
> add booking model and controller

- Gemfile
- Gemfile.lock
- app/models/user.rb
- db/schema.rb
- db/seeds.rb
DB:SEED => 5 users and 10 treehouses created, somehow there are only 8 treehouses though
> Seeding database

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/layouts/application.html.erb
- app/views/shared/_footer.html.erb
> updated footer

- Gemfile
- Gemfile.lock
- app/controllers/treehouses_controller.rb
- app/models/treehouse.rb
- app/views/treehouses/new.html.erb
- config/environments/development.rb
- config/storage.yml
- db/migrate/20220524133106_create_active_storage_tables.active_storage.rb
- db/schema.rb
implement cloudinary, also added the key to heroku, might not work for you localy since the cloudinary key is in my .env - also created the treehouses/new with basic simple form
> Cloudinary

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_treehouse_card.scss
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
redirections from logo and book now button
> redirections from logo and book now button

- app/controllers/bookings_controller.rb
- app/controllers/treehouses_controller.rb
- app/policies/booking_policy.rb
- app/views/treehouses/show.html.erb
- test/policies/booking_policy_test.rb
Added the Booking controller with pundit functionalitys
> booking controller

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_show_treehouse.scss
- app/assets/stylesheets/components/_treehouse_card.scss
- app/views/treehouses/index.html.erb
- app/views/treehouses/show.html.erb
first version of show page is done - feel free to review
> first version of showpage treehouse

- app/controllers/bookings_controller.rb
- app/controllers/dashboards_controller.rb
- app/policies/booking_policy.rb
- app/views/dashboards/index.html.erb
- config/routes.rb
- test/controllers/dashboards_controller_test.rb
- test/policies/dashboard_policy_test.rb
The Dashboard was added and tested
> added dashboard

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_sign_up_and_in.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
first version of sign in and sign up forms 
review pleaseeee
> first version of sign in and sign up forms

- app/assets/stylesheets/components/_footer.scss
- app/views/treehouses/index.html.erb
> margin added between footer and treehouse cards

- app/controllers/dashboards_controller.rb
- app/views/dashboards/index.html.erb
- app/views/treehouses/show.html.erb
Added the dashboard and tested it
> added dashboardcontroller

- app/controllers/bookings_controller.rb
- app/controllers/treehouses_controller.rb
I added feature to redirect to the treehouse/booking form if wrongly submitted
> add path in case of wrong form submitted

- app/assets/stylesheets/components/_dashboards.scss
- app/assets/stylesheets/components/_index.scss
- app/views/dashboards/index.html.erb
can you merge my pull request please pretty please
> first version of dashboard

- app/controllers/bookings_controller.rb
- app/controllers/treehouses_controller.rb
- app/models/booking.rb
- app/models/treehouse.rb
- app/policies/booking_policy.rb
- app/policies/treehouse_policy.rb
- app/views/treehouses/edit.html.erb
- app/views/treehouses/show.html.erb
- config/routes.rb
added destroy edit update and their policies + an edit view
> added destroy edit update and their policies + an edit view

- app/controllers/treehouses_controller.rb
- app/views/treehouses/edit.html.erb
> bugfixed routing after the deleting a treehouse

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_home.scss
- app/controllers/treehouses_controller.rb
- app/models/treehouse.rb
- app/views/pages/home.html.erb
- app/views/treehouses/index.html.erb
still need to style it, but it's responsive
> first version search bar

- app/assets/stylesheets/components/_dashboards.scss
- app/controllers/dashboards_controller.rb
- app/views/dashboards/index.html.erb
style my treehouses - add status to booking
> Dashboard fix

- app/assets/stylesheets/components/_show_treehouse.scss
- app/views/treehouses/edit.html.erb
- app/views/treehouses/show.html.erb
Minor changes to the button in the edit treehouse page and review format looks better know
> Minor changes buttons and the review v1

- app/controllers/reviews_controller.rb
- app/views/treehouses/show.html.erb
- config/routes.rb
minor changes to the bookings position
> minor changes to the bookings position

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
> new photo on homepage and more space between header and search bar

- app/views/reviews/index.html.erb
The right numbers of reviews gets displayed now
> reviews bugfix
